<?php
/**
 * CreditVerificationInformation
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  OotbTeam\MulPay
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * PGマルチペイメントサービス OpenAPIタイプ
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.5.0
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.9.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace OotbTeam\MulPay\Model;

use \ArrayAccess;
use \OotbTeam\MulPay\ObjectSerializer;

/**
 * CreditVerificationInformation Class Doc Comment
 *
 * @category Class
 * @package  OotbTeam\MulPay
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class CreditVerificationInformation implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'CreditVerificationInformation';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'tokenized_card' => '\OotbTeam\MulPay\Model\TokenizedCard',
        'credit_verification_options' => '\OotbTeam\MulPay\Model\CreditVerificationOptions',
        'onfile_card_options' => '\OotbTeam\MulPay\Model\OnfileCardOptions',
        'onfile_card' => '\OotbTeam\MulPay\Model\OnfileCard',
        'card' => '\OotbTeam\MulPay\Model\Card'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'tokenized_card' => null,
        'credit_verification_options' => null,
        'onfile_card_options' => null,
        'onfile_card' => null,
        'card' => null
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var boolean[]
      */
    protected static array $openAPINullables = [
        'tokenized_card' => false,
        'credit_verification_options' => false,
        'onfile_card_options' => false,
        'onfile_card' => false,
        'card' => false
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var boolean[]
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'tokenized_card' => 'tokenizedCard',
        'credit_verification_options' => 'creditVerificationOptions',
        'onfile_card_options' => 'onfileCardOptions',
        'onfile_card' => 'onfileCard',
        'card' => 'card'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'tokenized_card' => 'setTokenizedCard',
        'credit_verification_options' => 'setCreditVerificationOptions',
        'onfile_card_options' => 'setOnfileCardOptions',
        'onfile_card' => 'setOnfileCard',
        'card' => 'setCard'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'tokenized_card' => 'getTokenizedCard',
        'credit_verification_options' => 'getCreditVerificationOptions',
        'onfile_card_options' => 'getOnfileCardOptions',
        'onfile_card' => 'getOnfileCard',
        'card' => 'getCard'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->setIfExists('tokenized_card', $data ?? [], null);
        $this->setIfExists('credit_verification_options', $data ?? [], null);
        $this->setIfExists('onfile_card_options', $data ?? [], null);
        $this->setIfExists('onfile_card', $data ?? [], null);
        $this->setIfExists('card', $data ?? [], null);
    }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets tokenized_card
     *
     * @return \OotbTeam\MulPay\Model\TokenizedCard|null
     */
    public function getTokenizedCard()
    {
        return $this->container['tokenized_card'];
    }

    /**
     * Sets tokenized_card
     *
     * @param \OotbTeam\MulPay\Model\TokenizedCard|null $tokenized_card トークン化されたカード情報   **有効性確認(/credit/verifyCard)においては、Apple Payトークンは利用できません。**
     *
     * @return self
     */
    public function setTokenizedCard($tokenized_card)
    {
        if (is_null($tokenized_card)) {
            throw new \InvalidArgumentException('non-nullable tokenized_card cannot be null');
        }
        $this->container['tokenized_card'] = $tokenized_card;

        return $this;
    }

    /**
     * Gets credit_verification_options
     *
     * @return \OotbTeam\MulPay\Model\CreditVerificationOptions|null
     */
    public function getCreditVerificationOptions()
    {
        return $this->container['credit_verification_options'];
    }

    /**
     * Sets credit_verification_options
     *
     * @param \OotbTeam\MulPay\Model\CreditVerificationOptions|null $credit_verification_options credit_verification_options
     *
     * @return self
     */
    public function setCreditVerificationOptions($credit_verification_options)
    {
        if (is_null($credit_verification_options)) {
            throw new \InvalidArgumentException('non-nullable credit_verification_options cannot be null');
        }
        $this->container['credit_verification_options'] = $credit_verification_options;

        return $this;
    }

    /**
     * Gets onfile_card_options
     *
     * @return \OotbTeam\MulPay\Model\OnfileCardOptions|null
     */
    public function getOnfileCardOptions()
    {
        return $this->container['onfile_card_options'];
    }

    /**
     * Sets onfile_card_options
     *
     * @param \OotbTeam\MulPay\Model\OnfileCardOptions|null $onfile_card_options onfile_card_options
     *
     * @return self
     */
    public function setOnfileCardOptions($onfile_card_options)
    {
        if (is_null($onfile_card_options)) {
            throw new \InvalidArgumentException('non-nullable onfile_card_options cannot be null');
        }
        $this->container['onfile_card_options'] = $onfile_card_options;

        return $this;
    }

    /**
     * Gets onfile_card
     *
     * @return \OotbTeam\MulPay\Model\OnfileCard|null
     */
    public function getOnfileCard()
    {
        return $this->container['onfile_card'];
    }

    /**
     * Sets onfile_card
     *
     * @param \OotbTeam\MulPay\Model\OnfileCard|null $onfile_card 登録されているカード情報   **有効性確認(/credit/verifyCard)においては、登録済みのApple Pay情報は利用できません。**
     *
     * @return self
     */
    public function setOnfileCard($onfile_card)
    {
        if (is_null($onfile_card)) {
            throw new \InvalidArgumentException('non-nullable onfile_card cannot be null');
        }
        $this->container['onfile_card'] = $onfile_card;

        return $this;
    }

    /**
     * Gets card
     *
     * @return \OotbTeam\MulPay\Model\Card|null
     */
    public function getCard()
    {
        return $this->container['card'];
    }

    /**
     * Sets card
     *
     * @param \OotbTeam\MulPay\Model\Card|null $card card
     *
     * @return self
     */
    public function setCard($card)
    {
        if (is_null($card)) {
            throw new \InvalidArgumentException('non-nullable card cannot be null');
        }
        $this->container['card'] = $card;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet($offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


