<?php
/**
 * DuplicationCheckOptions
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  OotbTeam\MulPay
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * PGマルチペイメントサービス OpenAPIタイプ
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.5.0
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.9.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace OotbTeam\MulPay\Model;

use \ArrayAccess;
use \OotbTeam\MulPay\ObjectSerializer;

/**
 * DuplicationCheckOptions Class Doc Comment
 *
 * @category Class
 * @description 重複チェック情報   **成功取引、直接、トークン化の場合に指定が可能です。**   **トークン化の場合、MPクレカトークンのみ利用可能です。**
 * @package  OotbTeam\MulPay
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class DuplicationCheckOptions implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'DuplicationCheckOptions';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'enable_duplication_check' => 'bool',
        'include_deleted_cards' => 'bool',
        'excluded_member_ids' => 'string[]'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'enable_duplication_check' => null,
        'include_deleted_cards' => null,
        'excluded_member_ids' => null
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var boolean[]
      */
    protected static array $openAPINullables = [
        'enable_duplication_check' => false,
        'include_deleted_cards' => false,
        'excluded_member_ids' => false
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var boolean[]
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'enable_duplication_check' => 'enableDuplicationCheck',
        'include_deleted_cards' => 'includeDeletedCards',
        'excluded_member_ids' => 'excludedMemberIds'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'enable_duplication_check' => 'setEnableDuplicationCheck',
        'include_deleted_cards' => 'setIncludeDeletedCards',
        'excluded_member_ids' => 'setExcludedMemberIds'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'enable_duplication_check' => 'getEnableDuplicationCheck',
        'include_deleted_cards' => 'getIncludeDeletedCards',
        'excluded_member_ids' => 'getExcludedMemberIds'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->setIfExists('enable_duplication_check', $data ?? [], false);
        $this->setIfExists('include_deleted_cards', $data ?? [], false);
        $this->setIfExists('excluded_member_ids', $data ?? [], null);
    }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets enable_duplication_check
     *
     * @return bool|null
     */
    public function getEnableDuplicationCheck()
    {
        return $this->container['enable_duplication_check'];
    }

    /**
     * Sets enable_duplication_check
     *
     * @param bool|null $enable_duplication_check カード番号重複チェック   同じカード番号の登録を許可しない場合は`true`にします。   有効期限が同一かはチェックしません。   チェックの結果、すでに同じカード番号が登録されている場合は`invalid_request`エラーを返却します。
     *
     * @return self
     */
    public function setEnableDuplicationCheck($enable_duplication_check)
    {
        if (is_null($enable_duplication_check)) {
            throw new \InvalidArgumentException('non-nullable enable_duplication_check cannot be null');
        }
        $this->container['enable_duplication_check'] = $enable_duplication_check;

        return $this;
    }

    /**
     * Gets include_deleted_cards
     *
     * @return bool|null
     */
    public function getIncludeDeletedCards()
    {
        return $this->container['include_deleted_cards'];
    }

    /**
     * Sets include_deleted_cards
     *
     * @param bool|null $include_deleted_cards 重複チェックに削除カードを含めるか   カード番号重複チェック時の対象に削除済みカードを含める場合は`true`にします。
     *
     * @return self
     */
    public function setIncludeDeletedCards($include_deleted_cards)
    {
        if (is_null($include_deleted_cards)) {
            throw new \InvalidArgumentException('non-nullable include_deleted_cards cannot be null');
        }
        $this->container['include_deleted_cards'] = $include_deleted_cards;

        return $this;
    }

    /**
     * Gets excluded_member_ids
     *
     * @return string[]|null
     */
    public function getExcludedMemberIds()
    {
        return $this->container['excluded_member_ids'];
    }

    /**
     * Sets excluded_member_ids
     *
     * @param string[]|null $excluded_member_ids 重複チェック除外会員ID   設定した会員IDの一覧は、カード番号重複チェックの対象外にします。   最大20個まで設定可能です。
     *
     * @return self
     */
    public function setExcludedMemberIds($excluded_member_ids)
    {
        if (is_null($excluded_member_ids)) {
            throw new \InvalidArgumentException('non-nullable excluded_member_ids cannot be null');
        }
        $this->container['excluded_member_ids'] = $excluded_member_ids;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet($offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


