<?php
/**
 * FraudDetectionResult
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  OotbTeam\MulPay
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * PGマルチペイメントサービス OpenAPIタイプ
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.5.0
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.9.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace OotbTeam\MulPay\Model;

use \ArrayAccess;
use \OotbTeam\MulPay\ObjectSerializer;

/**
 * FraudDetectionResult Class Doc Comment
 *
 * @category Class
 * @description 不正検知の結果情報
 * @package  OotbTeam\MulPay
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class FraudDetectionResult implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'FraudDetectionResult';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'screening_type' => 'string',
        'screening_transaction_id' => 'string',
        'screening_result_code' => 'string',
        'screening_result_raw_data' => 'string'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'screening_type' => null,
        'screening_transaction_id' => null,
        'screening_result_code' => null,
        'screening_result_raw_data' => null
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var boolean[]
      */
    protected static array $openAPINullables = [
        'screening_type' => false,
        'screening_transaction_id' => false,
        'screening_result_code' => false,
        'screening_result_raw_data' => false
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var boolean[]
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'screening_type' => 'screeningType',
        'screening_transaction_id' => 'screeningTransactionId',
        'screening_result_code' => 'screeningResultCode',
        'screening_result_raw_data' => 'screeningResultRawData'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'screening_type' => 'setScreeningType',
        'screening_transaction_id' => 'setScreeningTransactionId',
        'screening_result_code' => 'setScreeningResultCode',
        'screening_result_raw_data' => 'setScreeningResultRawData'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'screening_type' => 'getScreeningType',
        'screening_transaction_id' => 'getScreeningTransactionId',
        'screening_result_code' => 'getScreeningResultCode',
        'screening_result_raw_data' => 'getScreeningResultRawData'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }

    public const SCREENING_TYPE_RED_SHIELD = 'RED_SHIELD';

    /**
     * Gets allowable values of the enum
     *
     * @return string[]
     */
    public function getScreeningTypeAllowableValues()
    {
        return [
            self::SCREENING_TYPE_RED_SHIELD,
        ];
    }

    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->setIfExists('screening_type', $data ?? [], null);
        $this->setIfExists('screening_transaction_id', $data ?? [], null);
        $this->setIfExists('screening_result_code', $data ?? [], null);
        $this->setIfExists('screening_result_raw_data', $data ?? [], null);
    }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        $allowedValues = $this->getScreeningTypeAllowableValues();
        if (!is_null($this->container['screening_type']) && !in_array($this->container['screening_type'], $allowedValues, true)) {
            $invalidProperties[] = sprintf(
                "invalid value '%s' for 'screening_type', must be one of '%s'",
                $this->container['screening_type'],
                implode("', '", $allowedValues)
            );
        }

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets screening_type
     *
     * @return string|null
     */
    public function getScreeningType()
    {
        return $this->container['screening_type'];
    }

    /**
     * Sets screening_type
     *
     * @param string|null $screening_type 審査タイプ
     *
     * @return self
     */
    public function setScreeningType($screening_type)
    {
        if (is_null($screening_type)) {
            throw new \InvalidArgumentException('non-nullable screening_type cannot be null');
        }
        $allowedValues = $this->getScreeningTypeAllowableValues();
        if (!in_array($screening_type, $allowedValues, true)) {
            throw new \InvalidArgumentException(
                sprintf(
                    "Invalid value '%s' for 'screening_type', must be one of '%s'",
                    $screening_type,
                    implode("', '", $allowedValues)
                )
            );
        }
        $this->container['screening_type'] = $screening_type;

        return $this;
    }

    /**
     * Gets screening_transaction_id
     *
     * @return string|null
     */
    public function getScreeningTransactionId()
    {
        return $this->container['screening_transaction_id'];
    }

    /**
     * Sets screening_transaction_id
     *
     * @param string|null $screening_transaction_id 審査トランザクションID
     *
     * @return self
     */
    public function setScreeningTransactionId($screening_transaction_id)
    {
        if (is_null($screening_transaction_id)) {
            throw new \InvalidArgumentException('non-nullable screening_transaction_id cannot be null');
        }
        $this->container['screening_transaction_id'] = $screening_transaction_id;

        return $this;
    }

    /**
     * Gets screening_result_code
     *
     * @return string|null
     */
    public function getScreeningResultCode()
    {
        return $this->container['screening_result_code'];
    }

    /**
     * Sets screening_result_code
     *
     * @param string|null $screening_result_code 審査結果コード
     *
     * @return self
     */
    public function setScreeningResultCode($screening_result_code)
    {
        if (is_null($screening_result_code)) {
            throw new \InvalidArgumentException('non-nullable screening_result_code cannot be null');
        }
        $this->container['screening_result_code'] = $screening_result_code;

        return $this;
    }

    /**
     * Gets screening_result_raw_data
     *
     * @return string|null
     */
    public function getScreeningResultRawData()
    {
        return $this->container['screening_result_raw_data'];
    }

    /**
     * Sets screening_result_raw_data
     *
     * @param string|null $screening_result_raw_data 審査結果(未加工)
     *
     * @return self
     */
    public function setScreeningResultRawData($screening_result_raw_data)
    {
        if (is_null($screening_result_raw_data)) {
            throw new \InvalidArgumentException('non-nullable screening_result_raw_data cannot be null');
        }
        $this->container['screening_result_raw_data'] = $screening_result_raw_data;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet($offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


