<?php
/**
 * StatusCredit
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  OotbTeam\MulPay
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * PGマルチペイメントサービス OpenAPIタイプ
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.5.0
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.9.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace OotbTeam\MulPay\Model;
use \OotbTeam\MulPay\ObjectSerializer;

/**
 * StatusCredit Class Doc Comment
 *
 * @category Class
 * @description クレカ払いの取引ステータス - &#x60;UNPROCESSED&#x60;：未決済 - &#x60;AUTHENTICATED&#x60;：未決済(3DS登録済) - &#x60;AUTH&#x60;：仮売上 - &#x60;CAPTURE&#x60;：即時売上 - &#x60;SALES&#x60;：実売上 - &#x60;CHECK&#x60;：有効性チェック - &#x60;CANCEL&#x60;：キャンセル
 * @package  OotbTeam\MulPay
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class StatusCredit
{
    /**
     * Possible values of this enum
     */
    public const UNPROCESSED = 'UNPROCESSED';

    public const AUTHENTICATED = 'AUTHENTICATED';

    public const AUTH = 'AUTH';

    public const CAPTURE = 'CAPTURE';

    public const SALES = 'SALES';

    public const CHECK = 'CHECK';

    public const CANCEL = 'CANCEL';

    /**
     * Gets allowable values of the enum
     * @return string[]
     */
    public static function getAllowableEnumValues()
    {
        return [
            self::UNPROCESSED,
            self::AUTHENTICATED,
            self::AUTH,
            self::CAPTURE,
            self::SALES,
            self::CHECK,
            self::CANCEL
        ];
    }
}


